# version: '3.8' # Latest best practice is to ommit a version number
services:
  kavita:
    image: kizaing/kavita:0.5.6
    container_name: kavita
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - ./media:/media
      - ./config:/kavita/config
    ports:
      - "50000:5000"
