version: '2.1'
services:
  trilium:
    image: zadam/trilium
    container_name: trilium
    restart: unless-stopped
    environment:
      - TRILIUM_DATA_DIR=/data
    ports:
      - "50001:8080"
    volumes:
      - ./trilium:/data
