# version: "2" # Latest best practice is to ommit a version number
services:
  homer:
    image: b4bz/homer:v22.08.1
    container_name: homer
    restart: unless-stopped
    volumes:
      - ./assets:/www/assets
    ports:
      - 50002:8080
    user: 1000:1000 # default
    environment:
      - INIT_ASSETS=1 # default
